// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/josepmdc/wikiodyssey/api"
	wiki2 "github.com/josepmdc/wikiodyssey/api/handlers/wiki"
	"github.com/josepmdc/wikiodyssey/api/services/wiki"
	"github.com/labstack/echo/v4"
)

// Injectors from wire.go:

func BuildApi() (*echo.Echo, error) {
	service := wiki.NewService()
	handler := wiki2.NewHandler(service)
	handlers := &api.Handlers{
		Handler: handler,
	}
	echoEcho := api.InitServer(handlers)
	return echoEcho, nil
}
